import React, { useState } from 'react';
import { BiTrash } from 'react-icons/bi';

import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { CardProduct } from '../components/CardProduct';
import { HeaderFavorites } from '../components/HeaderFavorites';
import { Modal } from '../components/Modal';
import { useCart } from '../hooks/useCart';
import styles from '../styles/pages/Cart.module.scss';

const Cart: NextPage = () => {
  const [modal, setModal] = useState(false);
  const [all, setAll] = useState(false);
  const [idProduct, setIdProduct] = useState(0);

  const { cart, clearCart, removeFromCart } = useCart();

  async function handleDeleteAll() {
    clearCart();
    setModal(false);
  }

  function handleCloseModal() {
    setAll(false);
    setModal(false);
  }

  async function handleDelete() {
    removeFromCart(idProduct);
    setModal(false);
  }

  async function cartRequestWhatsapp() {
    const url = `https://api.whatsapp.com/send?phone=82998394523&text=Olá,%20tenho%20interesse%20no%20produto%20${cart.map(
      (item) => item.name
    )}`;

    window.open(url, '_blank');
  }

  return (
    <>
      {modal && (
        <Modal
          handleDeleteProduct={() => handleDelete()}
          handleCloseModal={() => handleCloseModal()}
          handleDeleteAll={() => handleDeleteAll()}
          name={cart.find((product) => product.id === idProduct)?.name}
          all={all}
          cart={true}
        />
      )}
      <div className={styles.container}>
        <Head>
          <title>Dashboard</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main>
          <HeaderFavorites
            title="Carrinho"
            handleOnClick={() => {
              setAll(true);
              setModal(true);
            }}
          />
          <h2 className={styles.titleDishs}>Produtos</h2>
          <section className={styles.dishs}>
            {cart.length > 0 ? (
              cart.map((item) => (
                <section className={styles.wrapperProduct} key={item.id}>
                  <Link
                    href={{
                      pathname: '/products/[slug]',
                      query: { slug: item.id },
                    }}
                  >
                    <a>
                      <CardProduct
                        dish={{
                          id: item.id,
                          name: item.name,
                          price: item.price,
                          image: item.image,
                          quantity: item.quantity,
                          description: item.description,
                        }}
                      />
                    </a>
                  </Link>
                  <button
                    onClick={() => {
                      setIdProduct(item.id);
                      setModal(true);
                    }}
                  >
                    <section className={styles.wrapperDelete}>
                      <BiTrash size={24} color="#fff" />
                    </section>
                  </button>
                </section>
              ))
            ) : (
              <p>Nenhum produto no carrinho</p>
            )}
          </section>
          <section className={styles.footer}>
            <button
              onClick={() => {
                cartRequestWhatsapp();
              }}
              className={styles.buttonWhatsapp}
            >
              Finalizar compra
            </button>
            <button>
              <Link href="/">
                <a>Continuar comprando</a>
              </Link>
            </button>
          </section>
        </main>
      </div>
    </>
  );
};

export default Cart;
