import React, { useEffect, useState } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import { CardProduct } from '../components/CardProduct';
import { HeaderFavorites } from '../components/HeaderFavorites';
import styles from '../styles/pages/Home.module.scss';

type Product = {
  id: number;
  category: string;
  name: string;
  price: number;
  image: string;
  description: string;
};

const Favorites: NextPage = () => {
  const [products, setProducts] = useState<Product[]>([] as Product[]);

  useEffect(() => {
    async function getProducts() {
      const storageKey = '@FoodMenu:favorite';
      const productsStoraged: Product[] = await JSON.parse(
        localStorage.getItem(storageKey) || '[]'
      );
      setProducts(productsStoraged);
    }
    getProducts();
  }, []);

  async function handleDeleteAll() {
    localStorage.removeItem('@FoodMenu:favorite');
    setProducts([]);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <HeaderFavorites
          title="Favoritos"
          handleOnClick={() => handleDeleteAll()}
        />
        <h2 className={styles.titleDishs}>Pratos</h2>
        <section className={styles.dishs}>
          {products.length > 0 ? (
            products.map((item) => (
              <Link
                key={item.id}
                href={{
                  pathname: '/products/[slug]',
                  query: { slug: item.id },
                }}
              >
                <a>
                  <CardProduct
                    dish={{
                      id: item.id,
                      name: item.name,
                      price: item.price,
                      image: item.image,
                      description: item.description,
                    }}
                  />
                </a>
              </Link>
            ))
          ) : (
            <p>Nenhum prato favorito</p>
          )}
        </section>
      </main>
    </div>
  );
};

export default Favorites;
