import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/pages/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Hello next</h1>
      </main>
    </div>
  );
};

export default Home;
